SchedulerLite.Manager/Controllers/DelayTaskController.cs
using SchedulerLite.BLL;
using SchedulerLite.Model.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchedulerLite.Manager.Controllers
{
    public class DelayTaskController : Controller
    {
        // GET: DelayTask
        public ActionResult List(string name, int page = 1)
        {
            var pageSize = 10;
            var plist = B_DelayTask.SearchList(name, page, pageSize);
            ViewBag.plist = plist.ToStaticPagedList();
            return View();
        }

        public ActionResult Edit(long id = 0)
        {
            var m = B_DelayTask.SingleById(id);
            if (m == null)
            {
                m = new DelayTask();
                m.Enable = true;
                m.Method = "GET";
                m.TimeoutSeconds = 15;
                m.MaxRetryCount = 3;
                m.RetrySeconds = 30;
            }
            ViewBag.m = m;
            return View();
        }
        public ActionResult DoEdit(DelayTask m)
        {
            var ro = B_DelayTask.Edit(m);
            return Json(ro);
        }

        public ActionResult DoDelete(long id)
        {
            var ro = B_DelayTask.Delete(id);
            return Json(ro);
        }

        public ActionResult NewTask(DelayTask m)
        {
            var ro = B_DelayTask.Edit(m);
            return Json(ro);
        }
    }
}

SchedulerLite.Manager/Controllers/ExecuteLogController.cs
using SchedulerLite.BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchedulerLite.Manager.Controllers
{
    public class ExecuteLogController : Controller
    {
        // GET: ExecuteLog
        public ActionResult List(long taskId = 0, int taskType = 0, int status = 0, int page = 1)
        {
            var pageSize = 10;
            var plist = B_ExecuteLog.SearchList(taskId, taskType, status, page, pageSize);
            ViewBag.plist = plist.ToStaticPagedList();
            return View();
        }

    }
}

SchedulerLite.Manager/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchedulerLite.Manager.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

SchedulerLite.Manager/Controllers/TimedTaskController.cs
using SchedulerLite.BLL;
using SchedulerLite.Model.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchedulerLite.Manager.Controllers
{
    public class TimedTaskController : Controller
    {
        // GET: TimedTask
        public ActionResult List(string name, bool? enable, int page = 1)
        {
            var pageSize = 10;
            var plist = B_TimedTask.SearchList(name, enable, page, pageSize);
            ViewBag.plist = plist.ToStaticPagedList();
            return View();
        }

        public ActionResult Edit(long id = 0)
        {
            var m = B_TimedTask.SingleById(id);
            if (m == null)
            {
                m = new TimedTask();
                m.Enable = true;
                m.Method = "GET";
                m.TimeoutSeconds = 15;
            }
            ViewBag.m = m;
            return View();
        }
        public ActionResult DoEdit(TimedTask m)
        {
            var ro = B_TimedTask.Edit(m);
            return Json(ro);
        }

        public ActionResult DoDelete(long id)
        {
            var ro = B_TimedTask.Delete(id);
            return Json(ro);
        }
    }
}

SchedulerLite.Manager/Views/DelayTask/Edit.cshtml
@{
    ViewBag.Title = "编辑延迟任务";
    var m = ViewBag.m as DelayTask;
}

<form class="layui-form" id="frm" style="width:600px;">
    <input type="hidden" value="@m.Id" name="id" />
    <div class="layui-form-item">
        <label class="layui-form-label">任务名称：</label>
        <div class="layui-input-block">
            <input type="text" name="Name" value="@m.Name" required lay-verify="required" placeholder="任务名称" class="layui-input" />
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">任务地址：</label>
        <div class="layui-input-block">
            <input type="text" name="Url" value="@m.Url" required lay-verify="required" placeholder="任务地址" class="layui-input" />
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">请求方法：</label>
        <div class="layui-input-block">
            <input type="text" name="Method" value="@m.Method" required lay-verify="required" placeholder="请求方式GET或POST" class="layui-input" />
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">Post数据：</label>
        <div class="layui-input-block">
            <textarea class="layui-textarea" name="PostData">@m.PostData</textarea>
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">触发时间：</label>
        <div class="layui-input-block">
            <input type="text" name="TriggerTime" id="TriggerTime" value="@(m.TriggerTime== DateTime.MinValue?"":m.TriggerTime.ToString("yyyy-MM-dd HH:mm:ss"))" placeholder="成功标识" class="layui-input" />
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">成功标识：</label>
        <div class="layui-input-block">
            <input type="text" name="SuccessFlag" value="@m.SuccessFlag" placeholder="成功标识" class="layui-input" />
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">超时秒数：</label>
        <div class="layui-input-block">
            <input type="text" name="TimeoutSeconds" value="@m.TimeoutSeconds" required lay-verify="required" placeholder="请求超时秒数" class="layui-input" />
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">重试次数：</label>
        <div class="layui-input-block">
            <input type="text" name="MaxRetryCount" value="@m.MaxRetryCount" required lay-verify="required" placeholder="请求超时秒数" class="layui-input" />
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">延迟秒数：</label>
        <div class="layui-input-block">
            <input type="text" name="RetrySeconds" value="@m.RetrySeconds" required lay-verify="required" placeholder="请求超时秒数" class="layui-input" />
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">状态：</label>
        <div class="layui-input-block">
            <input type="checkbox" @(m.Enable ? "checked" : "") name="Enable" value="true" lay-skin="switch" lay-filter="switchTest" lay-text="开启|禁用">
        </div>
    </div>

    <div class="layui-form-item">
        <div class="layui-input-block">
            <button type="button" class="layui-btn" lay-submit lay-filter="btnSubmit">保存</button>
            <a class="layui-btn layui-btn-primary " href="@Url.Action("list")">取消</a>
        </div>
    </div>
</form>


@section scripts{
    <script>

        layui.laydate.render({ elem: "#TriggerTime", type: 'datetime' });
           //监听提交
        layui.form.on('submit(btnSubmit)', function (data) {
            $.post("@Url.Action("doedit")", data.field, function (ro) {
                alert(ro.Msg);
                if (ro.Success) {
                    location.href = '@Url.Action("list")';
                }
            });
            return false;
        });
    </script>
}

SchedulerLite.Manager/Views/DelayTask/List.cshtml
@{
    ViewBag.Title = "延迟任务列表";
    ViewBag.nav = "delayTask";
    var plist = ViewBag.plist as StaticPagedList<DelayTask>;
}

<a class="layui-btn layui-btn-danger layui-btn-sm" href="@Url.Action("edit")">
    <i class="layui-icon">&#xe654;</i>
    任务
</a>

<hr />

<form method="get" class="layui-form">

    <label>名称：</label>
    <div class="layui-input-inline">
        <input type="text" name="name" id="name" value="@Request["name"]" class="layui-input" />
    </div>
    <button class="layui-btn">查询</button>
</form>

<table class="layui-table">
    <thead>
        <tr>
            <th>编号</th>
            <th>名称</th>
            <th>url</th>
            <th>方法</th>
            <th>数据</th>
            <th>执行次数</th>
            <th>重试次数</th>
            <th>重试秒数</th>
            <th>超时秒数</th>
            <th>成功标识</th>
            <th>添加时间</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in plist)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Url</td>
                <td>@item.Method</td>
                <td>@item.PostData</td>
                <td>@item.ExecCount</td>
                <td>@item.RetryCount/@item.MaxRetryCount</td>
                <td>@item.RetrySeconds</td>
                <td>@item.TimeoutSeconds</td>
                <td>@item.SuccessFlag</td>
                <td>@item.AddTime.ToString("yyyy-MM-dd HH:mm:ss")</td>
                <td>
                    <div class="layui-btn-group">
                        <button class="layui-btn layui-btn-sm layui-btn-danger" type="button" onclick="del(@item.Id)">删除</button>
                        <a class="layui-btn layui-btn-sm layui-btn-normal" href="@Url.Action("list","executelog",new { taskType=2, taskId=item.Id})">日志</a>
                        <a class="layui-btn layui-btn-sm" href="@Url.Action("edit",new { id=item.Id})">修改</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@Html.PagedListPager(plist)

@section scripts{
    <script>
        function del(id) {
            if (confirm("确定要删除吗?")) {
                $.post("@Url.Action("dodelete")", { id: id }, function (ro) {
                    alert(ro.Msg);
                    if (ro.Success) {
                        location.reload();
                    }
                });
            }
        }
    </script>
}

SchedulerLite.Manager/Views/ExecuteLog/List.cshtml
@{
    ViewBag.Title = "日志";
    ViewBag.nav = "log";
    var plist = ViewBag.plist as StaticPagedList<ExecuteLog>;
}


<form method="get" class="layui-form">

    <label>任务编号：</label>
    <div class="layui-input-inline">
        <input type="text" name="taskId" id="taskId" value="@Request["taskId"]" class="layui-input" />
    </div>
    <div class="layui-input-inline">
        <select class="sel" name="taskType">
            <option value="">-任务类型-</option>
            <option @("1".Equals(Request["taskType"]) ? "selected" : "") value="1">定时任务</option>
            <option @("2".Equals(Request["taskType"]) ? "selected" : "") value="2">延迟任务</option>
        </select>
    </div>
    <div class="layui-input-inline">
        <select class="sel" name="status">
            <option value="">-状态-</option>
            <option @("1".Equals(Request["status"]) ? "selected" : "") value="1">成功</option>
            <option @("2".Equals(Request["status"]) ? "selected" : "") value="2">失败</option>
            <option @("3".Equals(Request["status"]) ? "selected" : "") value="3">超时</option>
        </select>
    </div>

    <button class="layui-btn">查询</button>
</form>

<table class="layui-table">
    <thead>
        <tr>
            <th>编号</th>
            <th>任务编号</th>
            <th>名称</th>
            <th>类型</th>
            <th>任务url</th>
            <th>方法</th>
            <th>请求数据</th>
            <th>执行状态</th>
            <th>详细</th>
            <th>添加时间</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in plist)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.TaskId</td>
                <td>@item.TaskName</td>
                <td>@item.TaskType</td>
                <td>@item.TaskUrl</td>
                <td>@item.TaskMethod</td>
                <td>@item.PostData</td>
                <td>@item.GetStatus()</td>
                <td>@item.Message</td>
                <td>@item.AddTime.ToString("yyyy-MM-dd HH:mm:ss")</td>
            </tr>
        }
    </tbody>
</table>

@Html.PagedListPager(plist)

SchedulerLite.Manager/Views/Home/Index.cshtml
@{
    ViewBag.Title = "welcome";
}

SchedulerLite.Manager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 任务调度系统</title>

    <link href="~/Scripts/layui/css/layui.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
</head>
<body class="layui-layout-body">
    <div class="layui-layout layui-layout-admin">
        <div class="layui-header">
            <div class="layui-logo">任务调度系统</div>
            <!-- 头部区域（可配合layui已有的水平导航） -->
            @*<ul class="layui-nav layui-layout-right">
                    <li class="layui-nav-item"><a href="">退出</a></li>
                </ul>*@
        </div>
        <div class="layui-side layui-bg-black">
            <div class="layui-side-scroll">
                <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
                <ul class="layui-nav layui-nav-tree">
                    <li class="layui-nav-item layui-nav-itemed">
                        <a class="" href="javascript:;">任务</a>
                        <dl class="layui-nav-child">
                            <dd class="@("timedTask".Equals(ViewBag.nav)?"layui-this":"")"><a href="@Url.Action("list","timedTask")">定时任务</a></dd>
                            <dd class="@("delayTask".Equals(ViewBag.nav)?"layui-this":"")"><a href="@Url.Action("list","delayTask")">延迟任务</a></dd>
                            <dd class="@("log".Equals(ViewBag.nav)?"layui-this":"")"><a href="@Url.Action("list","ExecuteLog")">任务日志</a></dd>
                        </dl>
                    </li>
                </ul>
            </div>
        </div>

        <div class="layui-body">
            <!-- 内容主体区域 -->
            <div style="padding: 15px;">
                @RenderBody()
            </div>
        </div>

        <div class="layui-footer">
            <!-- 底部固定区域 -->
            © 2018
        </div>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/layui/layui.all.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

SchedulerLite.Manager/Views/TimedTask/Edit.cshtml
@{
    ViewBag.Title = "编辑定时任务";
    var m = ViewBag.m as TimedTask;
}




<form class="layui-form" id="frm" style="width:600px;">
    <input type="hidden" value="@m.Id" name="id" />
    <div class="layui-form-item">
        <label class="layui-form-label">任务名称：</label>
        <div class="layui-input-block">
            <input type="text" name="Name" value="@m.Name" required lay-verify="required" placeholder="任务名称" class="layui-input" />
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">
            <a href="http://www.pppet.net/" target="_blank" class="link">
                cron：
            </a>
        </label>
        <div class="layui-input-block">
            <input type="text" name="Cron" value="@m.Cron" required lay-verify="required" placeholder="cron表达式" class="layui-input" />

        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">任务地址：</label>
        <div class="layui-input-block">
            <input type="text" name="Url" value="@m.Url" required lay-verify="required" placeholder="任务地址" class="layui-input" />
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">请求方法：</label>
        <div class="layui-input-block">
            <input type="text" name="Method" value="@m.Method" required lay-verify="required" placeholder="请求方式GET或POST" class="layui-input" />
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">Post数据：</label>
        <div class="layui-input-block">
            <textarea class="layui-textarea" name="PostData">@m.PostData</textarea>
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">成功标识：</label>
        <div class="layui-input-block">
            <input type="text" name="SuccessFlag" value="@m.SuccessFlag"  placeholder="成功标识" class="layui-input" />
        </div>
    </div>
    
    <div class="layui-form-item">
        <label class="layui-form-label">超时秒数：</label>
        <div class="layui-input-block">
            <input type="text" name="TimeoutSeconds" value="@m.TimeoutSeconds" required lay-verify="required" placeholder="请求超时秒数" class="layui-input" />
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">状态：</label>
        <div class="layui-input-block">
            <input type="checkbox" @(m.Enable ? "checked" : "") name="Enable" value="true" lay-skin="switch" lay-filter="switchTest" lay-text="开启|禁用">
        </div>
    </div>

    <div class="layui-form-item">
        <div class="layui-input-block">
            <button type="button" class="layui-btn" lay-submit lay-filter="btnSubmit">保存</button>
            <a class="layui-btn layui-btn-primary " href="@Url.Action("list")">取消</a>
        </div>
    </div>
</form>


@section scripts{
    <script>
           //监听提交
        layui.form.on('submit(btnSubmit)', function (data) {
            $.post("@Url.Action("doedit")", data.field, function (ro) {
                alert(ro.Msg);
                if (ro.Success) {
                    location.href = '@Url.Action("list")';
                }
            });
            return false;
        });
    </script>
}

SchedulerLite.Manager/Views/TimedTask/List.cshtml
@{
    ViewBag.Title = "定时任务列表";
    ViewBag.nav = "timedTask";
    var plist = ViewBag.plist as StaticPagedList<TimedTask>;
}

<a class="layui-btn layui-btn-danger layui-btn-sm" href="@Url.Action("edit")">
    <i class="layui-icon">&#xe654;</i>
    任务
</a>

<hr />



<form method="get" class="layui-form">

    <label>名称：</label>
    <div class="layui-input-inline">
        <input type="text" name="name" id="name" value="@Request["name"]" class="layui-input" />
    </div>
    <div class="layui-input-inline">
        <select class="sel" name="enable">
            <option value="">-状态-</option>
            <option @("true".Equals(Request["enable"]) ? "selected" : "") value="true">启用</option>
            <option @("false".Equals(Request["enable"]) ? "selected" : "") value="false">禁用</option>
        </select>
    </div>
    <button class="layui-btn">查询</button>
</form>

<table class="layui-table">
    <thead>
        <tr>
            <th>编号</th>
            <th>名称</th>
            <th>cron</th>
            <th>url</th>
            <th>方法</th>
            <th>数据</th>
            <th>执行次数</th>
            <th>执行时间</th>
            <th>执行状态</th>
            <th>成功标识</th>
            <th>状态</th>
            <th>添加时间</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in plist)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Cron</td>
                <td>@item.Url</td>
                <td>@item.Method</td>
                <td>@item.PostData</td>
                <td>@item.ExecCount</td>
                <td>@item.LastExecTime</td>
                <td>
                    @item.GetStatus()
                </td>
                <td>@item.SuccessFlag</td>
                <td>@(item.Enable ? "启用" : "禁用")</td>
                <td>@item.AddTime.ToString("yyyy-MM-dd HH:mm:ss")</td>
                <td>
                    <div class="layui-btn-group">
                        <button class="layui-btn layui-btn-sm layui-btn-danger" type="button" onclick="del(@item.Id)">删除</button>
                        <a class="layui-btn layui-btn-sm layui-btn-normal" href="@Url.Action("list","executelog",new { taskType=1, taskId=item.Id})">日志</a>
                        <a class="layui-btn layui-btn-sm" href="@Url.Action("edit",new { id=item.Id})">修改</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@Html.PagedListPager(plist)

@section scripts{
    <script>
        function del(id) {
            if (confirm("确定要删除吗?")) {
                $.post("@Url.Action("dodelete")", { id: id }, function (ro) {
                    alert(ro.Msg);
                    if (ro.Success) {
                        location.reload();
                    }
                });
            }
        }
    </script>
}